#name: Release Drafter
#
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, reopened, synchronize]
#
#permissions:
#  contents: read
#
#jobs:
#  update_release_draft:
#    permissions:
#      contents: write  # for release-drafter/release-drafter to create a github release
#      pull-requests: write  # for release-drafter/release-drafter to add label to PR
#    runs-on: ubuntu-latest
#    steps:
#      - uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
name: Auto Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
